name: Cl

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo " " >> README.md
          git config user.name {{USERNAME}}
          git config user.email {{EMAIL}}
          git add .
          git commit -m "Always green!"
      - name : Push changes
        env: 
          PAT: ${{secrets.PAT}}
        run: |
          git remote set-url origin https://$ACTIONS_PAT@github.com/elulcao/all-green.git
          git push origin main
